### ISSUE TITLE
Create a submodule with a relative URL

### ISSUE THREAD

**Issue by evanrittenhouse** [python-poetry/test-fixture-vcs-repository#3]
Wondering if anyone can create a submodule in this repo with a relative URL? The submodule should be in the `python-poetry` repo, IMHO, but I don't have access to create it. If you'd rather I create my own, please let me know how that should integrate with the existing Poetry integration test suite.

 This is in reference to [#6499](https://github.com/python-poetry/poetry/issues/6499) in the core repo. I need a Git submodule to check that `tests/integration/test_utils_vcs_git.py` works properly, as the existing Git tests check against remote.

CC @neersighted as I've spoken to you on this issue.

**Comment by neersighted** [comment]
I think you mean "org" where you say "repo". Regardless, if you need a dummy submodule on this org, why not just use this repo (but on a different branch or old commit) to define the submodule?

I can set that up if that will work for your purposes.

**Comment by evanrittenhouse** [comment]
Yeah, that'd be great. Thanks.

**Comment by neersighted** [comment]
The branch `standalone_branch` is now available to use as a relative ref submodule.
